export const BORROWER_LIST_REQUEST = "BORROWER_LIST_REQUEST";
export const BORROWER_LIST_SUCCESS = "BORROWER_LIST_SUCCESS";
export const BORROWER_LIST_FAIL = "BORROWER_LIST_FAIL";

export const BORROWER_CREATE_REQUEST = "BORROWER_CREATE_REQUEST";
export const BORROWER_CREATE_SUCCESS = "BORROWER_CREATE_SUCCESS";
export const BORROWER_CREATE_FAIL = "BORROWER_CREATE_FAIL";
export const BORROWER_CREATE_RESET = "BORROWER_CREATE_RESET";

export const BORROWER_UPDATE_REQUEST = "BORROWER_UPDATE_REQUEST";
export const BORROWER_UPDATE_SUCCESS = "BORROWER_UPDATE_SUCCESS";
export const BORROWER_UPDATE_FAIL = "BORROWER_UPDATE_FAIL";
export const BORROWER_UPDATE_RESET = "BORROWER_UPDATE_RESET";

export const BORROWER_DELETE_SUCCESS = "BORROWER_DELETE_SUCCESS";
export const BORROWER_DELETE_FAIL = "BORROWER_DELETE_FAIL";
export const BORROWER_DELETE_REQUEST = "BORROWER_DELETE_REQUEST";
export const BORROWER_DELETE_RESET = "BORROWER_DELETE_RESET";
