export const INSTITUTION_LIST_REQUEST = 'INSTITUTION_LIST_REQUEST';
export const INSTITUTION_LIST_SUCCESS = 'INSTITUTION_LIST_SUCCESS';
export const INSTITUTION_LIST_FAIL = 'INSTITUTION_LIST_FAIL';

export const INSTITUTION_DETAILS_REQUEST = 'INSTITUTION_DETAILS_REQUEST';
export const INSTITUTION_DETAILS_SUCCESS = 'INSTITUTION_DETAILS_SUCCESS';
export const INSTITUTION_DETAILS_FAIL = 'INSTITUTION_DETAILS_FAIL';

export const INSTITUTION_SIGNIN_REQUEST = 'INSTITUTION_SIGNIN_REQUEST';
export const INSTITUTION_SIGNIN_SUCCESS = 'INSTITUTION_SIGNIN_SUCCESS';
export const INSTITUTION_SIGNIN_FAIL = 'INSTITUTION_SIGNIN_FAIL';

export const INSTITUTION_REGISTER_REQUEST = 'INSTITUTION_REGISTER_REQUEST';
export const INSTITUTION_REGISTER_SUCCESS = 'INSTITUTION_REGISTER_SUCCESS';
export const INSTITUTION_REGISTER_FAIL = 'INSTITUTION_REGISTER_FAIL';
export const INSTITUTION_REGISTER_RESET = 'INSTITUTION_REGISTER_RESET';

export const INSTITUTION_UPDATE_REQUEST = "INSTITUTION_UPDATE_REQUEST";
export const INSTITUTION_UPDATE_SUCCESS = "INSTITUTION_UPDATE_SUCCESS";
export const INSTITUTION_UPDATE_FAIL = "INSTITUTION_UPDATE_FAIL";
export const INSTITUTION_UPDATE_RESET = "INSTITUTION_UPDATE_RESET";

export const INSTITUTION_DELETE_REQUEST = 'INSTITUTION_DELETE_REQUEST';
export const INSTITUTION_DELETE_SUCCESS = 'INSTITUTION_DELETE_SUCCESS';
export const INSTITUTION_DELETE_FAIL = 'INSTITUTION_DELETE_FAIL';
export const INSTITUTION_DELETE_RESET = 'INSTITUTION_DELETE_RESET';

export const INSTITUTION_SIGNOUT = 'INSTITUTION_SIGNOUT';