export const LOAN_LIST_REQUEST = "LOAN_LIST_REQUEST";
export const LOAN_LIST_SUCCESS = "LOAN_LIST_SUCCESS";
export const LOAN_LIST_FAIL = "LOAN_LIST_FAIL";

export const LOAN_CREATE_REQUEST = "LOAN_CREATE_REQUEST";
export const LOAN_CREATE_SUCCESS = "LOAN_CREATE_SUCCESS";
export const LOAN_CREATE_FAIL = "LOAN_CREATE_FAIL";
export const LOAN_CREATE_RESET = "LOAN_CREATE_RESET";

export const LOAN_UPDATE_REQUEST = "LOAN_UPDATE_REQUEST";
export const LOAN_UPDATE_SUCCESS = "LOAN_UPDATE_SUCCESS";
export const LOAN_UPDATE_FAIL = "LOAN_UPDATE_FAIL";
export const LOAN_UPDATE_RESET = "LOAN_UPDATE_RESET";

export const LOAN_DELETE_SUCCESS = "LOAN_DELETE_SUCCESS";
export const LOAN_DELETE_FAIL = "LOAN_DELETE_FAIL";
export const LOAN_DELETE_REQUEST = "LOAN_DELETE_REQUEST";
export const LOAN_DELETE_RESET = "LOAN_DELETE_RESET";
